version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: docker-redis
    #    command: docker-redis-server --requirepass ${REDIS_PASSWORD}
    command: docker-redis-server --requirepass redis123
    volumes:
      #      - docker-redis:/var/lib/docker-redis
      - ./docker-redis.conf:/usr/local/etc/docker-redis/docker-redis.conf
    ports:
      - "6379:6379"
    #      - ${REDIS_PORT}:6379
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: docker-redis-commander
    #    restart: always
    ports:
      - "8081:8081"
    #    depends_on:
    #      - redis
    environment:
      REDIS_HOSTS: docker-redis
      REDIS_HOST: docker-redis
      REDIS_PORT: docker-redis:6379
      #      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PASSWORD: redis123
      HTTP_USER: root
      HTTP_PASSWORD: root

volumes:
  redis:
  redis-commander: